### ISSUE TITLE
Created the demo through OpenShift Online - KIEScanner timer doesn't run

### ISSUE THREAD

**Issue by alberttwong** [jbossdemocentral/brms-coolstore-demo#30]
I created the demo through OpenShift Online.   Was able to update decision table, version it, version the project, deploy out to server.   I've been waiting for a bit but the KIEScanner time doesn't go off so the new artifact doesn't get deployed.  What am I missing that you did on your video?

**Comment by eschabell** [comment]
The online cartridge is based on 6.0.2 product, that is not a smooth as the current 6.1 versions. If you do not see the KieScanner triggering then you most likely are not using a Large gear? This is the only one that allows that version to start a separate thread for the scanner...

**Comment by alberttwong** [comment]
I'm using a large gear.

**Comment by alberttwong** [comment]
2015/07/16 15:28:10,468 INFO  [stdout] (http-/127.9.246.1:8080-5) com.vaadin.ui.Button$ClickEvent[source=true]
2015/07/16 15:28:42,250 INFO  [org.drools.compiler.kie.builder.impl.KieRepositoryImpl] (http-/127.9.246.1:8080-1) KieModule was added:MemoryKieModule[ ReleaseId=com.redhat:coolstore:2.1.0]
2015/07/16 15:29:02,552 INFO  [org.drools.compiler.kie.builder.impl.KieRepositoryImpl] (http-/127.9.246.1:8080-1) KieModule was added:MemoryKieModule[ ReleaseId=com.redhat:coolstore:2.1.0]
2015/07/16 15:29:21,368 INFO  [stdout] (http-/127.9.246.1:8080-1) com.vaadin.ui.Button$ClickEvent[source=true]
2015/07/16 20:20:49,386 INFO  [stdout] (http-/127.9.246.1:8080-6) com.vaadin.ui.Button$ClickEvent[source=true]
2015/07/16 20:48:55,864 INFO  [org.guvnor.common.services.builder.ResourceChangeIncrementalBuilder] (Thread-86) Incremental build request received for: default://master@coolstore-demo/coolstore/pom.xml (updated).
2015/07/16 20:48:55,951 INFO  [org.guvnor.common.services.builder.ResourceChangeIncrementalBuilder] (Thread-106) Incremental build request being processed: PathImpl{uri='default://master@coolstore-demo/coolstore', fileName='coolstore', attrs={}} (updated).
2015/07/16 20:48:57,677 INFO  [org.drools.compiler.kie.builder.impl.KieRepositoryImpl] (Thread-106) KieModule was added:MemoryKieModule[ ReleaseId=com.redhat:coolstore:2.1.1]
2015/07/16 20:49:05,746 INFO  [org.drools.compiler.kie.builder.impl.KieRepositoryImpl] (http-/127.9.246.1:8080-1) KieModule was added:MemoryKieModule[ ReleaseId=com.redhat:coolstore:2.1.1]
2015/07/16 20:49:19,398 INFO  [stdout] (http-/127.9.246.1:8080-1) com.vaadin.ui.Button$ClickEvent[source=true]

**Comment by eschabell** [comment]
I don't see the KieScanner picking anything up, but it is also only BRMS 6.0.2 available on OpenShift until v3 cartridge is made available. Might just want to retry creating the gear from scratch... and you are using this backing project?

https://github.com/jbossdemocentral/cartridge-bpmPaaS-coolstore-demo

**Comment by alberttwong** [comment]
I created two projects.   

Project A used the OpenShift one click install

Project B used the YAML custom cartridge at https://raw.githubusercontent.com/eschabell/cartridge-bpmPaaS-coolstore-demo/master/metadata/manifest.yml

Both do not kick off the KIEScanner.

**Comment by alberttwong** [comment]
Project C used the OpenShift one click install from https://github.com/jbossdemocentral/cartridge-bpmPaaS-coolstore-demo

This also did not kick off KIEScanner.

**Comment by eschabell** [comment]
I will take a look when I get a chance...

**Comment by alberttwong** [comment]
I validated that the local install installation works correctly - KIEScanner (Timer) fires off.

**Comment by eschabell** [comment]
Expecting the problem is online product version of 6.0.2, the patch used in the local install fixes these issues and will be propagated when v3 is released.
