### ISSUE TITLE
For complex event processing - do we have an example that shows monitoring a stream?

### ISSUE THREAD

**Issue by alberttwong** [jbossdemocentral/brms-coolstore-demo#33]
I saw that we're using complex event processing for monitoring promo codes.  Do we have something that shows multiple stream and for us to monitoring specific events or sequential events (eg. like monitoring credit card fraud)?

**Comment by eschabell** [comment]
Not here, but on MOJO CoP they have a very complex one for HA and CEP.

**Comment by alberttwong** [comment]
I see.  This is a common scenario that (multiple event processing) that customers ask about quite often (just had them ask last week).   I didn't have a demo so I could only talk to it.
