### ISSUE TITLE
Error loading in project into JBoss Developer Studio

### ISSUE THREAD

**Issue by alberttwong** [jbossdemocentral/brms-coolstore-demo#35]
Cannot compile the project. 

Description	Resource	Path	Location	Type
Referenced file contains errors (http://docs.jboss.org/cdi/beans_1_0.xsd).  For more information, right click on the message in the Problems View and select "Show Details..."	beans.xml	/brms-coolstore-demo/src/main/webapp/WEB-INF	line 1	XML Problem

**Comment by alberttwong** [comment]
The errors below were detected when validating the file "beans_1_0.xsd" via the file "beans.xml".  In most cases these errors can be detected by validating "beans_1_0.xsd" directly.  However it is possible that errors will only occur when beans_1_0.xsd is validated in the context of beans.xml.

**Comment by jmilliro** [comment]
It's only validation warning.   Should work fine.

Thanks,

Jason Milliron
Senior Solutions Architect
JBoss by Red Hat, Inc.
jason.milliron@redhat.com


-----Original Message-----

**Comment by alberttwong** [comment]
It's in error... I'm fixing it right now and will push.

**Comment by alberttwong** [comment]
Patch submitted.

**Comment by eschabell** [comment]
Thanks for sorting this out, patches merged.
