### ISSUE TITLE
Install failure on vaadin dependency...

### ISSUE THREAD

**Issue by eschabell** [jbossdemocentral/brms-coolstore-demo#48]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 30:19 min
[INFO] Finished at: 2016-03-23T17:23:42-04:00
[INFO] Final Memory: 30M/530M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.vaadin:vaadin-maven-plugin:7.6.0:update-theme (default) on project brms-coolstore-demo: Execution default of goal com.vaadin:vaadin-maven-plugin:7.6.0:update-theme failed: Plugin com.vaadin:vaadin-maven-plugin:7.6.0 or one of its dependencies could not be resolved: Could not transfer artifact xerces:xercesImpl:jar:2.9.1 from/to central (https://repo.maven.apache.org/maven2): GET request of: xerces/xercesImpl/2.9.1/xercesImpl-2.9.1.jar from central failed: Read timed out -> [Help 1]

**Comment by amahdy** [comment]
Sounds like connection problem with the maven repo.
What is the result of `mvn update`?

**Comment by eschabell** [comment]
Yep, my bad, closing out as today it builds fine.
