### ISSUE TITLE
Does JBoss EAP patches require a RH subscription?

### ISSUE THREAD

**Issue by dmarrazzo** [jbossdemocentral/brms-coolstore-demo#49]
Hello Eric,
I was following your guidelines to build the demo in my workspace but maven requires
`jboss-eap-6.4.4-installer.jar` that is not freely accessible.
Is it possible to overcome this issue?
Thank you

**Comment by eschabell** [comment]
It should require 6.0.0 installer jar and then you have a separate 6.4.4 patch zip. Yes you need subscriptions to obtains these patches. If you still want to explore this demo, look for released (tags) versions in the readme that match what you can obtain.
