### ISSUE TITLE
Add a date to shipping costs decision table

### ISSUE THREAD

**Issue by eschabell** [jbossdemocentral/brms-coolstore-demo#5]
In viewing these video's, it prompted a question.  In part III
  you updated the shipping amount in the decision table.  Can
  you create a decision table with an effective date, so you
  could make that change, validate and build it, but it would
  only take effect based on the date?  In this way, you could
  have the new decision table take effect with specific timing.
   Same concept with promotions, where you could have a
  promotion take effect, and even end on a particular date.

**Comment by alberttwong** [comment]
I would add to this scenario.  Problem is that when you have pricing rules, the pricing changes constantly and you when you do a refund, you need to price them at the time of purchase, not what the rules are currently.   If that is the case, how do we solve this?   Versions?  No rule gets turned off and all of them are active?    Branching at the flow level?   Lots of questions.
