### ISSUE TITLE
Error in startup with BPM Suite 6.3 version

### ISSUE THREAD

**Issue by eschabell** [jbossdemocentral/brms-coolstore-demo#55]
Using java 1.8.0_45, osX, after init.sh getting this warning followed by this error (see attached server log):

22:10:12,152 WARN  [org.guvnor.m2repo.backend.server.GuvnorM2Repository](MSC service thread 1-8) Could not find artifact org.guvnor:guvnor-asset-mgmt-project:jar:6.4.0.Final-redhat-3 in guvnor-m2-repo (file:/Users/erics/demo-projects/brms/brms-coolstore-demo/target/jboss-eap-6.4/bin/): org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact org.guvnor:guvnor-asset-mgmt-project:jar:6.4.0.Final-redhat-3 in guvnor-m2-repo (file:/Users/erics/demo-projects/brms/brms-coolstore-demo/target/jboss-eap-6.4/bin/)

22:10:13,737 ERROR [org.kie.api.builder.KieScanner](MSC service thread 1-8) Unable to create MavenProject from InputStream: org.apache.maven.project.ProjectBuildingException: 1 problem was encountered while building the effective model for org.guvnor:guvnor-asset-mgmt-project:[unknown-version]
[FATAL] Non-resolvable parent POM: Could not find artifact org.guvnor:guvnor-asset-mgmt:pom:6.4.0.Final-redhat-3 in central (https://repo.maven.apache.org/maven2) @ line 4, column 11
 for project org.guvnor:guvnor-asset-mgmt-project:[unknown-version]

Wiped entire maven repo and installed fresh build, repeated same errors above.

Demo seems to work fine from my quick inspection and testing of the decision table shipping as example updates to ensure KieScanner is picking up the changes. Not sure what effect the error has?

[sever-log.txt](https://github.com/jbossdemocentral/brms-coolstore-demo/files/322065/sever-log.txt)

**Comment by jaenswart** [comment]
https://issues.jboss.org/browse/RHBRMS-2447

**Comment by DuncanDoyle** [comment]
Yeah, known issue in the product and already logged. I really can't do much about this, other than having users add the product Maven repo to their settings.xml, which I really don't want to do (too much hassle to setup, makes the demo harder to run).

I'll keep the ticket open (as I still think it's an issue) and will close when we've got a product update that fixes it.

**Comment by rbourner** [comment]
Would it be possible to add 2 more features to this demo: 
- a couple of DSL verbalized rules as the guided editor is not always suited for BAs as it is still somehow technical.
- a couple of examples of enumeration (both for a guided Decision Table and a DSL). It doesn't need to be linked to an external datasource, hard-coded would be ok.

**Comment by DuncanDoyle** [comment]
@rbourner I've created 2 new issues to track those requests:

#58 
#59

**Comment by DuncanDoyle** [comment]
Should be fixed with the upgrade to 6.4: https://github.com/jbossdemocentral/brms-coolstore-demo/commit/9a00021bbd9258bc9a33e20fadbb532948a98a9d 

Closing this issue.
