### ISSUE TITLE
Can't lunch http://localhost:8080/brms-coolstore-demo/

### ISSUE THREAD

**Issue by evilas** [jbossdemocentral/brms-coolstore-demo#63]
Something is wrong with vaadin framework. I got this msg:

The widgetset cloud still hadn't compiled your widgetset. Depending on usage, this may take 0.5 - n minutes. Would you like to try again?
and...

Failed to load the widgetset: http://wscdn.vaadin.com/ws/wse3f1b3b7b58092b80bafad85a7a69ba7/wse3f1b3b7b58092b80bafad85a7a69ba7.nocache.js

I tried to run a mvn clean install but doesn't work.

Help pls! thanks in advance

**Comment by DuncanDoyle** [comment]
Sorry for the late reply.  I've had more reports of this not working correctly. Looking at the widgetset URL, that file can't be found. 

Unfortuntaly I don't know a lot about Vaadin, so would need to dive into it. Unfortunately I can't see to reproduce this on my own machine.

Can you tell me what kind of system you're running this on? (OS, JVM, etc.).

**Comment by evilas** [comment]
Hi Duncan,
                   OSX, JAVA build 1.8.0_102-b14, chrome, jboss-bpmsuite-installer-6.2.0.BZ-1299002.jar, jboss-eap-6.4.0-installer.jar, jboss-eap-6.4.4-patch.zip

Thanks, Eduardo.

**Comment by evilas** [comment]
Duncan,  sorry I took the data from the wrong directory.

This is the correct one:

jboss-brms-6.3.0.GA-installer.jar
jboss-eap-6.4.0-installer.jar
jboss-eap-6.4.7-patch.zip

Thanks, Eduardo.

**Comment by DuncanDoyle** [comment]
What language settings do you use? I got some reports from colleagues in France that were having the same problem. Do you use a language setting other than English in your browser?

**Comment by evilas** [comment]
English (United States) in my browser and in the laptop.

**Comment by rbourner** [comment]
Hi Duncan,
As I told you, 3 people in France on 3 different machines got the problem.
I am using MacOS, JDK 1.7, BRMS 6.3.0.GA.
One other person is using RHEL, I don't know about the 3rd.
I tried on Chrome, Safari and Firefox, no difference.
I tried changing the locale in the JVM and the language in Chrome, no difference.

**Comment by DuncanDoyle** [comment]
OK, I've now been able to reproduce this on my machine as well. Will look into this ASAP.

**Comment by DuncanDoyle** [comment]
Should be fixed on master now. Please let me know if you any further issues. Thanks @mstahv

**Comment by evilas** [comment]
works fine!

Kudos!

Thanks, Edu.
