### ISSUE TITLE
docker repo, do I need to add one?

### ISSUE THREAD

**Issue by rgupta1234** [jbossdemocentral/brms-coolstore-demo#81]
[rgupta@rgupta brms-coolstore-demo-master]$ sudo docker build -t jbossdemocentral/brms-coolstore-demo .
Sending build context to Docker daemon 386.8 MB
Sending build context to Docker daemon
Step 0 : FROM jbossdemocentral/developer:jdk8-uid
Pulling repository jbossdemocentral/developer
INFO[0003] Could not reach any registry endpoint       
[rgupta@rgupta brms-coolstore-demo-master]$

The following steps can be used to configure and run the demo in a container

    Download and unzip.

    Add products installs directory.

    Copy contents of support/docker directory to the project root.

    Build demo image

    docker build -t jbossdemocentral/brms-coolstore-demo .

**Comment by DuncanDoyle** [comment]
You need to have access to Docker hub. The Dockerfile uses a FROM: https://github.com/jbossdemocentral/brms-coolstore-demo/blob/master/support/docker/Dockerfile#L2

So, you need to be able to pull the "jbossdemocentral/developer:jdk8-uid" image from DockerHub.

**Comment by DuncanDoyle** [comment]
Is this still an issue? Can we close it?
